### ISSUE TITLE
values.yaml file in deploy stages

### ISSUE THREAD

**Issue by mehran-prs** [saharsh-samples/dotnet-k8s-helm-cicd#30]
Where should we keep our helm `values.yaml` file to provide to the Deploy stages?
I think it's good to include it in your `deploy` stages.

**Comment by saharshsingh** [comment]
Sorry for the late response @mehran-prs. In this example, I had placed it in the [deployment/helm-k8s](https://github.com/saharsh-samples/dotnet-k8s-helm-cicd/tree/develop/deployment/helm-k8s) folder. This location can be overridden for the Jenkinsfile with the [helmChartDirectory](https://github.com/saharsh-samples/dotnet-k8s-helm-cicd/blob/2216dec110f5ce314587a9cb2bee39d9b372feba/Jenkinsfile#L15) parameter.
